# Generated by Django 4.2 on 2024-02-27 07:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0004_category_created_category_modified_comment_created_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='category',
            old_name='name',
            new_name='title',
        ),
        migrations.RenameField(
            model_name='product',
            old_name='name',
            new_name='title',
        ),
    ]
