# Generated by Django 4.2 on 2024-02-27 07:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0006_comment_is_confirmed'),
    ]

    operations = [
        migrations.RenameField(
            model_name='subject',
            old_name='name',
            new_name='title',
        ),
    ]
