# Generated by Django 4.2 on 2024-02-27 07:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0002_order_is_paid'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='order',
            options={'ordering': ('-pk',)},
        ),
    ]
